export const EXERCISES = [
  "Bench Press",
  "Incline Press",
  "Shoulder Press",
  "Lateral Raise",
  "Tricep Pushdown",
  "Squat",
  "Leg Press",
  "Romanian Deadlift",
  "Leg Curl",
  "Leg Extension",
  "Calf Raise",
  "Deadlift",
  "Pull-up",
  "Barbell Row",
  "Cable Row",
  "Lat Pulldown",
  "Bicep Curl",
  "Other",
] as const;
